/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
/**
 *
 * @author spider
 */
public class AddDiagnosisInformation extends javax.swing.JFrame {
    public int flag=0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName());

    /**
     * Creates new form AddDiagnosisInformation
     */
    public AddDiagnosisInformation() {
        initComponents();
        jLabel2.setVisible(false);
        jLabel8.setVisible(false);
        wardCombo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SympField = new javax.swing.JTextField();
        MedicField = new javax.swing.JTextField();
        DiagField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        wardCombo = new javax.swing.JComboBox<>();
        SaveBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PatientID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 42, 80, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 36, 101, -1));

        SearchBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search.png"))); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(this::SearchBtnActionPerformed);
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 32, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "PatientID", "Name", "Contact No.", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, 650, 53));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("PatientID does not exist");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 71, 179, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Symptom's");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Diagnosis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 309, 78, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Medicines");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 364, 78, -1));

        SympField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SympField.addActionListener(this::SympFieldActionPerformed);
        getContentPane().add(SympField, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 257, 236, -1));

        MedicField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedicField.addActionListener(this::MedicFieldActionPerformed);
        getContentPane().add(MedicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 358, 236, -1));

        DiagField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiagField.addActionListener(this::DiagFieldActionPerformed);
        getContentPane().add(DiagField, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 306, 236, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ward Required ?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Type of ward");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 309, 121, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Yes");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 258, 92, -1));

        wardCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wardCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo" }));
        getContentPane().add(wardCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 306, -1, -1));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/save-icon--1.png"))); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(this::SaveBtnActionPerformed);
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 462, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Close.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(this::CloseBtnActionPerformed);
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 462, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add new patient background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
    String patientID = jTextField1.getText();
     if (patientID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a Patient ID to search!");
            return;
        }
     try (Connection con = ConnectionProvider.getConnection()) {
            String sql = "SELECT * FROM patient WHERE patientID = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, patientID);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            if (!rs.next()) {
                jLabel2.setVisible(true);
                flag = 0;
            } else {
                jLabel2.setVisible(false);
                Object[] row = {
                    rs.getString("patientID"),
                    rs.getString("name"),
                    rs.getString("contactNumber"),
                    rs.getInt("age"),
                    rs.getString("gender"),
                    rs.getString("bloodGroup"),
                    rs.getString("address"),
                    rs.getString("anyMajorDisease")
                };
                model.addRow(row);
                flag = 1;
                jTextField1.setEditable(false);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error:\n" + e.getMessage());
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void SympFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SympFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SympFieldActionPerformed

    private void MedicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicFieldActionPerformed

    private void DiagFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiagFieldActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if(flag==1){
        String PatientID=jTextField1.getText();
        String symptom=SympField.getText();
        String diagnosis=MedicField.getText();
        String medicines=DiagField.getText();
        
        String wardReq;
        String typeWard;
                if(jCheckBox1.isSelected()){
                    wardReq="Yes";
                    typeWard=(String)wardCombo.getSelectedItem();
                }
                else{
                        wardReq="No";
                        typeWard="";

                }
                if (!PatientID.trim().isEmpty()) {

    try {
        Connection con = ConnectionProvider.getConnection();

        String sql =
        "INSERT INTO patientreport (patientID, symptom, diagnosis, medicines, wardReq, typeWard) "
        + "VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, PatientID);
        ps.setString(2, symptom);
        ps.setString(3, diagnosis);
        ps.setString(4, medicines);
        ps.setString(5, wardReq);      
        ps.setString(6, typeWard); 

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Successfully Updated");
        setVisible(false);
        new AddDiagnosisInformation().setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }

} else {
    JOptionPane.showMessageDialog(null, "Patient ID Field is empty");
}
    }//GEN-LAST:event_SaveBtnActionPerformed
    }
    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
       setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jLabel8.setVisible(true);
            wardCombo.setVisible(true);
        }
        else{
            jLabel8.setVisible(false);
            wardCombo.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddDiagnosisInformation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField DiagField;
    private javax.swing.JTextField MedicField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SympField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> wardCombo;
    // End of variables declaration//GEN-END:variables
}
