/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Youssef
 */
public class AddNewPatientRecord extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName());

    /**
     * Creates new form AddNewPatientRecord
     */
    public AddNewPatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PatIdField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        ContactNoField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        BloodField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        GenderCombo = new javax.swing.JComboBox<>();
        MoreField = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Close.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(this::CloseBtnActionPerformed);
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 26));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 26));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, 26));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Any Major Disease Suffered Earlier");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 430, -1));

        PatIdField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(PatIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 290, -1));

        NameField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameField.addActionListener(this::NameFieldActionPerformed);
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 290, -1));

        ContactNoField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(ContactNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 290, -1));

        AgeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(AgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 290, -1));

        BloodField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(BloodField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 290, -1));

        AddressField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 290, -1));

        GenderCombo.setEditable(true);
        GenderCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(GenderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 290, -1));

        MoreField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(MoreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 430, 40));

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/save-icon--1.png"))); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(this::SaveBtnActionPerformed);
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add new patient background.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

        String PatientID = PatIdField.getText();
        String Name = NameField.getText();
        String ContactNo = ContactNoField.getText();
        String Age = AgeField.getText();
        String Gender = (String) GenderCombo.getSelectedItem();
        String BloodGroup = BloodField.getText();
        String Address = AddressField.getText();
        String AnyMajorDis = MoreField.getText();

    
    if (PatientID.isEmpty() || Name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Patient ID and Name are required");
        return;
    }
     try (Connection con = ConnectionProvider.getConnection()) {

        String sql = "INSERT INTO patient "
                   + "(patientID, name, contactNumber, age, gender, bloodGroup, address, anyMajorDisease) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, PatientID);
        ps.setString(2, Name);
        ps.setString(3, ContactNo); 
        ps.setInt(4, Integer.parseInt(Age)); 
        ps.setString(5, Gender);
        ps.setString(6, BloodGroup);
        ps.setString(7, Address);
        ps.setString(8, AnyMajorDis);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Patient Saved Successfully");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Age must be a number");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }        
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewPatientRecord().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField AgeField;
    private javax.swing.JTextField BloodField;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField ContactNoField;
    private javax.swing.JComboBox<String> GenderCombo;
    private javax.swing.JTextField MoreField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PatIdField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
