/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Youssef
 */
public class home extends javax.swing.JFrame {
    public int i =0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArrowBtn = new javax.swing.JButton();
        AddNewPatientBtn = new javax.swing.JButton();
        AddDiagBtn = new javax.swing.JButton();
        FullHistoryBtn = new javax.swing.JButton();
        UpdBtn = new javax.swing.JButton();
        HospitBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ArrowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/two arrow.png"))); // NOI18N
        ArrowBtn.addActionListener(this::ArrowBtnActionPerformed);
        getContentPane().add(ArrowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        AddNewPatientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add new patient.png"))); // NOI18N
        AddNewPatientBtn.setText("Add New Patient Record");
        AddNewPatientBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddNewPatientBtn.addActionListener(this::AddNewPatientBtnActionPerformed);
        getContentPane().add(AddNewPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        AddDiagBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add diag.png"))); // NOI18N
        AddDiagBtn.setText("Add Diagnosis Info");
        AddDiagBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddDiagBtn.addActionListener(this::AddDiagBtnActionPerformed);
        getContentPane().add(AddDiagBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        FullHistoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_hospital_information.png"))); // NOI18N
        FullHistoryBtn.setText("Full History of Patient");
        FullHistoryBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        FullHistoryBtn.addActionListener(this::FullHistoryBtnActionPerformed);
        getContentPane().add(FullHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        UpdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_update_details.png"))); // NOI18N
        UpdBtn.setText("Update Patient Record");
        UpdBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        UpdBtn.addActionListener(this::UpdBtnActionPerformed);
        getContentPane().add(UpdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        HospitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_history1.png"))); // NOI18N
        HospitBtn.setText("Hospital Information");
        HospitBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        HospitBtn.addActionListener(this::HospitBtnActionPerformed);
        getContentPane().add(HospitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/exit.png"))); // NOI18N
        LogOutBtn.setText("Log out");
        LogOutBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        LogOutBtn.addActionListener(this::LogOutBtnActionPerformed);
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrowBtnActionPerformed
        if (i==0){
            AddNewPatientBtn.setLocation(90, 30) ;
            AddDiagBtn.setLocation(333, 30) ;
            FullHistoryBtn.setLocation(576, 30) ;
            UpdBtn.setLocation(819, 30) ;
            HospitBtn.setLocation(1062, 30) ;
            LogOutBtn.setLocation(1062, 89) ;
            i = 1;
        }
        else{
            AddNewPatientBtn.setLocation(10, 107) ;
            AddDiagBtn.setLocation(10, 184) ;
            FullHistoryBtn.setLocation(10, 261) ;
            UpdBtn.setLocation(10, 338) ;
            HospitBtn.setLocation(10, 415) ;
            LogOutBtn.setLocation(10, 490) ;
        i=0;
        }
    }//GEN-LAST:event_ArrowBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void HospitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitBtnActionPerformed
       new AboutHospital().setVisible(true);
    }//GEN-LAST:event_HospitBtnActionPerformed

    private void FullHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullHistoryBtnActionPerformed
       new FullHistoryOfThePatient().setVisible(true);
    }//GEN-LAST:event_FullHistoryBtnActionPerformed

    private void AddDiagBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDiagBtnActionPerformed
        new AddDiagnosisInformation().setVisible(true);
    }//GEN-LAST:event_AddDiagBtnActionPerformed

    private void AddNewPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPatientBtnActionPerformed
        new AddNewPatientRecord().setVisible(true);
    }//GEN-LAST:event_AddNewPatientBtnActionPerformed

    private void UpdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdBtnActionPerformed
        new updatePatientRecord().setVisible(true);
    }//GEN-LAST:event_UpdBtnActionPerformed
    
        
        
                                       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDiagBtn;
    private javax.swing.JButton AddNewPatientBtn;
    private javax.swing.JButton ArrowBtn;
    private javax.swing.JButton FullHistoryBtn;
    private javax.swing.JButton HospitBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton UpdBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
